### ISSUE TITLE
i18n RegExp problem in FAQ page

### ISSUE THREAD

**Issue by aspect** [aspectron/sia-tech#2]
@surinder83singh we have a problem with i18n regexp resolving some text because of the variable naming in JS code of the faq.ejs

This line containing _T-END causes i18n to choke on regexp string extraction as such:

![image](https://cloud.githubusercontent.com/assets/7544020/15876040/fcd66124-2cd8-11e6-8ee0-e644f463ddaa.png)

Can you please look at the code and either replace _T-END with something else or alter regexp pattern in i18n (but we have to be **very careful** touching regexp in i18n as any mistake can render text not searchable and can damage translations).

Please look at this ASAP

**Comment by aspect** [comment]
Please be careful with i18n.data because it already contains Chinese translations.

**Comment by surinder83singh** [comment]
fixed by changing ejs tpl
